// Generated by gencpp from file carla_tracking/TrackedObject.msg
// DO NOT EDIT!


#ifndef CARLA_TRACKING_MESSAGE_TRACKEDOBJECT_H
#define CARLA_TRACKING_MESSAGE_TRACKEDOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace carla_tracking
{
template <class ContainerAllocator>
struct TrackedObject_
{
  typedef TrackedObject_<ContainerAllocator> Type;

  TrackedObject_()
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , track_id(0)
    , class_id(0)
    , confidence(0.0)
    , distance(0.0)
    , velocity(0.0)  {
    }
  TrackedObject_(const ContainerAllocator& _alloc)
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , track_id(0)
    , class_id(0)
    , confidence(0.0)
    , distance(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef float _x1_type;
  _x1_type x1;

   typedef float _y1_type;
  _y1_type y1;

   typedef float _x2_type;
  _x2_type x2;

   typedef float _y2_type;
  _y2_type y2;

   typedef int32_t _track_id_type;
  _track_id_type track_id;

   typedef int32_t _class_id_type;
  _class_id_type class_id;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::carla_tracking::TrackedObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carla_tracking::TrackedObject_<ContainerAllocator> const> ConstPtr;

}; // struct TrackedObject_

typedef ::carla_tracking::TrackedObject_<std::allocator<void> > TrackedObject;

typedef boost::shared_ptr< ::carla_tracking::TrackedObject > TrackedObjectPtr;
typedef boost::shared_ptr< ::carla_tracking::TrackedObject const> TrackedObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carla_tracking::TrackedObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carla_tracking::TrackedObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carla_tracking::TrackedObject_<ContainerAllocator1> & lhs, const ::carla_tracking::TrackedObject_<ContainerAllocator2> & rhs)
{
  return lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1 &&
    lhs.x2 == rhs.x2 &&
    lhs.y2 == rhs.y2 &&
    lhs.track_id == rhs.track_id &&
    lhs.class_id == rhs.class_id &&
    lhs.confidence == rhs.confidence &&
    lhs.distance == rhs.distance &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carla_tracking::TrackedObject_<ContainerAllocator1> & lhs, const ::carla_tracking::TrackedObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carla_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carla_tracking::TrackedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carla_tracking::TrackedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_tracking::TrackedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_tracking::TrackedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_tracking::TrackedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_tracking::TrackedObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carla_tracking::TrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6680634a5eec139a85714bade9173e43";
  }

  static const char* value(const ::carla_tracking::TrackedObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6680634a5eec139aULL;
  static const uint64_t static_value2 = 0x85714bade9173e43ULL;
};

template<class ContainerAllocator>
struct DataType< ::carla_tracking::TrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carla_tracking/TrackedObject";
  }

  static const char* value(const ::carla_tracking::TrackedObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carla_tracking::TrackedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 跟踪目标自定义消息\n"
"float32 x1          # 边界框左上角x\n"
"float32 y1          # 边界框左上角y\n"
"float32 x2          # 边界框右下角x\n"
"float32 y2          # 边界框右下角y\n"
"int32 track_id      # 跟踪ID\n"
"int32 class_id      # 类别ID\n"
"float32 confidence  # 置信度\n"
"float32 distance    # 距离（米）\n"
"float32 velocity    # 速度\n"
;
  }

  static const char* value(const ::carla_tracking::TrackedObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carla_tracking::TrackedObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
      stream.next(m.track_id);
      stream.next(m.class_id);
      stream.next(m.confidence);
      stream.next(m.distance);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackedObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carla_tracking::TrackedObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carla_tracking::TrackedObject_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x1: ";
    Printer<float>::stream(s, indent + "  ", v.x1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y1: ";
    Printer<float>::stream(s, indent + "  ", v.y1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x2: ";
    Printer<float>::stream(s, indent + "  ", v.x2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y2: ";
    Printer<float>::stream(s, indent + "  ", v.y2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "track_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.track_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "class_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.class_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARLA_TRACKING_MESSAGE_TRACKEDOBJECT_H
