// Generated by gencpp from file carla_autonomous/Reset.msg
// DO NOT EDIT!


#ifndef CARLA_AUTONOMOUS_MESSAGE_RESET_H
#define CARLA_AUTONOMOUS_MESSAGE_RESET_H

#include <ros/service_traits.h>


#include <carla_autonomous/ResetRequest.h>
#include <carla_autonomous/ResetResponse.h>


namespace carla_autonomous
{

struct Reset
{

typedef ResetRequest Request;
typedef ResetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reset
} // namespace carla_autonomous


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::carla_autonomous::Reset > {
  static const char* value()
  {
    return "203da5fa4570387c68513683b6bcbd59";
  }

  static const char* value(const ::carla_autonomous::Reset&) { return value(); }
};

template<>
struct DataType< ::carla_autonomous::Reset > {
  static const char* value()
  {
    return "carla_autonomous/Reset";
  }

  static const char* value(const ::carla_autonomous::Reset&) { return value(); }
};


// service_traits::MD5Sum< ::carla_autonomous::ResetRequest> should match
// service_traits::MD5Sum< ::carla_autonomous::Reset >
template<>
struct MD5Sum< ::carla_autonomous::ResetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::carla_autonomous::Reset >::value();
  }
  static const char* value(const ::carla_autonomous::ResetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::carla_autonomous::ResetRequest> should match
// service_traits::DataType< ::carla_autonomous::Reset >
template<>
struct DataType< ::carla_autonomous::ResetRequest>
{
  static const char* value()
  {
    return DataType< ::carla_autonomous::Reset >::value();
  }
  static const char* value(const ::carla_autonomous::ResetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::carla_autonomous::ResetResponse> should match
// service_traits::MD5Sum< ::carla_autonomous::Reset >
template<>
struct MD5Sum< ::carla_autonomous::ResetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::carla_autonomous::Reset >::value();
  }
  static const char* value(const ::carla_autonomous::ResetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::carla_autonomous::ResetResponse> should match
// service_traits::DataType< ::carla_autonomous::Reset >
template<>
struct DataType< ::carla_autonomous::ResetResponse>
{
  static const char* value()
  {
    return DataType< ::carla_autonomous::Reset >::value();
  }
  static const char* value(const ::carla_autonomous::ResetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARLA_AUTONOMOUS_MESSAGE_RESET_H
