// Generated by gencpp from file carla_autonomous/StartEpisodeRequest.msg
// DO NOT EDIT!


#ifndef CARLA_AUTONOMOUS_MESSAGE_STARTEPISODEREQUEST_H
#define CARLA_AUTONOMOUS_MESSAGE_STARTEPISODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace carla_autonomous
{
template <class ContainerAllocator>
struct StartEpisodeRequest_
{
  typedef StartEpisodeRequest_<ContainerAllocator> Type;

  StartEpisodeRequest_()
    : success(false)
    , message()  {
    }
  StartEpisodeRequest_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StartEpisodeRequest_

typedef ::carla_autonomous::StartEpisodeRequest_<std::allocator<void> > StartEpisodeRequest;

typedef boost::shared_ptr< ::carla_autonomous::StartEpisodeRequest > StartEpisodeRequestPtr;
typedef boost::shared_ptr< ::carla_autonomous::StartEpisodeRequest const> StartEpisodeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator1> & lhs, const ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator1> & lhs, const ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace carla_autonomous

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carla_autonomous/StartEpisodeRequest";
  }

  static const char* value(const ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
;
  }

  static const char* value(const ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StartEpisodeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::carla_autonomous::StartEpisodeRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARLA_AUTONOMOUS_MESSAGE_STARTEPISODEREQUEST_H
