// Generated by gencpp from file carla_autonomous/StartEpisode.msg
// DO NOT EDIT!


#ifndef CARLA_AUTONOMOUS_MESSAGE_STARTEPISODE_H
#define CARLA_AUTONOMOUS_MESSAGE_STARTEPISODE_H

#include <ros/service_traits.h>


#include <carla_autonomous/StartEpisodeRequest.h>
#include <carla_autonomous/StartEpisodeResponse.h>


namespace carla_autonomous
{

struct StartEpisode
{

typedef StartEpisodeRequest Request;
typedef StartEpisodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartEpisode
} // namespace carla_autonomous


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::carla_autonomous::StartEpisode > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::carla_autonomous::StartEpisode&) { return value(); }
};

template<>
struct DataType< ::carla_autonomous::StartEpisode > {
  static const char* value()
  {
    return "carla_autonomous/StartEpisode";
  }

  static const char* value(const ::carla_autonomous::StartEpisode&) { return value(); }
};


// service_traits::MD5Sum< ::carla_autonomous::StartEpisodeRequest> should match
// service_traits::MD5Sum< ::carla_autonomous::StartEpisode >
template<>
struct MD5Sum< ::carla_autonomous::StartEpisodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::carla_autonomous::StartEpisode >::value();
  }
  static const char* value(const ::carla_autonomous::StartEpisodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::carla_autonomous::StartEpisodeRequest> should match
// service_traits::DataType< ::carla_autonomous::StartEpisode >
template<>
struct DataType< ::carla_autonomous::StartEpisodeRequest>
{
  static const char* value()
  {
    return DataType< ::carla_autonomous::StartEpisode >::value();
  }
  static const char* value(const ::carla_autonomous::StartEpisodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::carla_autonomous::StartEpisodeResponse> should match
// service_traits::MD5Sum< ::carla_autonomous::StartEpisode >
template<>
struct MD5Sum< ::carla_autonomous::StartEpisodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::carla_autonomous::StartEpisode >::value();
  }
  static const char* value(const ::carla_autonomous::StartEpisodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::carla_autonomous::StartEpisodeResponse> should match
// service_traits::DataType< ::carla_autonomous::StartEpisode >
template<>
struct DataType< ::carla_autonomous::StartEpisodeResponse>
{
  static const char* value()
  {
    return DataType< ::carla_autonomous::StartEpisode >::value();
  }
  static const char* value(const ::carla_autonomous::StartEpisodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARLA_AUTONOMOUS_MESSAGE_STARTEPISODE_H
