// Generated by gencpp from file carla_autonomous/Stop.msg
// DO NOT EDIT!


#ifndef CARLA_AUTONOMOUS_MESSAGE_STOP_H
#define CARLA_AUTONOMOUS_MESSAGE_STOP_H

#include <ros/service_traits.h>


#include <carla_autonomous/StopRequest.h>
#include <carla_autonomous/StopResponse.h>


namespace carla_autonomous
{

struct Stop
{

typedef StopRequest Request;
typedef StopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Stop
} // namespace carla_autonomous


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::carla_autonomous::Stop > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::carla_autonomous::Stop&) { return value(); }
};

template<>
struct DataType< ::carla_autonomous::Stop > {
  static const char* value()
  {
    return "carla_autonomous/Stop";
  }

  static const char* value(const ::carla_autonomous::Stop&) { return value(); }
};


// service_traits::MD5Sum< ::carla_autonomous::StopRequest> should match
// service_traits::MD5Sum< ::carla_autonomous::Stop >
template<>
struct MD5Sum< ::carla_autonomous::StopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::carla_autonomous::Stop >::value();
  }
  static const char* value(const ::carla_autonomous::StopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::carla_autonomous::StopRequest> should match
// service_traits::DataType< ::carla_autonomous::Stop >
template<>
struct DataType< ::carla_autonomous::StopRequest>
{
  static const char* value()
  {
    return DataType< ::carla_autonomous::Stop >::value();
  }
  static const char* value(const ::carla_autonomous::StopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::carla_autonomous::StopResponse> should match
// service_traits::MD5Sum< ::carla_autonomous::Stop >
template<>
struct MD5Sum< ::carla_autonomous::StopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::carla_autonomous::Stop >::value();
  }
  static const char* value(const ::carla_autonomous::StopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::carla_autonomous::StopResponse> should match
// service_traits::DataType< ::carla_autonomous::Stop >
template<>
struct DataType< ::carla_autonomous::StopResponse>
{
  static const char* value()
  {
    return DataType< ::carla_autonomous::Stop >::value();
  }
  static const char* value(const ::carla_autonomous::StopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARLA_AUTONOMOUS_MESSAGE_STOP_H
