// Generated by gencpp from file carla_autonomous/StopRequest.msg
// DO NOT EDIT!


#ifndef CARLA_AUTONOMOUS_MESSAGE_STOPREQUEST_H
#define CARLA_AUTONOMOUS_MESSAGE_STOPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace carla_autonomous
{
template <class ContainerAllocator>
struct StopRequest_
{
  typedef StopRequest_<ContainerAllocator> Type;

  StopRequest_()
    {
    }
  StopRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::carla_autonomous::StopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::carla_autonomous::StopRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StopRequest_

typedef ::carla_autonomous::StopRequest_<std::allocator<void> > StopRequest;

typedef boost::shared_ptr< ::carla_autonomous::StopRequest > StopRequestPtr;
typedef boost::shared_ptr< ::carla_autonomous::StopRequest const> StopRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::carla_autonomous::StopRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::carla_autonomous::StopRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace carla_autonomous

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::carla_autonomous::StopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::carla_autonomous::StopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_autonomous::StopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::carla_autonomous::StopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_autonomous::StopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::carla_autonomous::StopRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::carla_autonomous::StopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::carla_autonomous::StopRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::carla_autonomous::StopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "carla_autonomous/StopRequest";
  }

  static const char* value(const ::carla_autonomous::StopRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::carla_autonomous::StopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::carla_autonomous::StopRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::carla_autonomous::StopRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::carla_autonomous::StopRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::carla_autonomous::StopRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CARLA_AUTONOMOUS_MESSAGE_STOPREQUEST_H
