# Hyperparameters.py - 修复版
# 深度强化学习超参数配置

DISCOUNT = 0.97

FPS = 60

MEMORY_FRACTION = 0.35

REWARD_OFFSET = -100

MIN_REPLAY_MEMORY_SIZE = 1_000

REPLAY_MEMORY_SIZE = 20_000

MINIBATCH_SIZE = 64  # 减小批次大小以提高稳定性

PREDICTION_BATCH_SIZE = 1

TRAINING_BATCH_SIZE = MINIBATCH_SIZE // 4

EPISODES = 300  # 减少训练轮次以快速测试

SECONDS_PER_EPISODE = 60

MIN_EPSILON = 0.05

EPSILON = 1.0

EPSILON_DECAY = 0.995

MODEL_NAME = "YY_Optimized_v3"

MIN_REWARD = -100

UPDATE_TARGET_EVERY = 15

AGGREGATE_STATS_EVERY = 5

SHOW_PREVIEW = False

IM_WIDTH = 160

IM_HEIGHT = 120

SLOW_COUNTER = 330

LOW_REWARD_THRESHOLD = -2

SUCCESSFUL_THRESHOLD = 3

LEARNING_RATE = 0.0001

# PER参数
PER_ALPHA = 0.7
PER_BETA_START = 0.5
PER_BETA_FRAMES = 50000

# 训练策略参数
USE_CURRICULUM_LEARNING = True
USE_MULTI_OBJECTIVE = True
USE_IMITATION_LEARNING = False

# 课程学习参数
CURRICULUM_STAGES = 6
CURRICULUM_SUCCESS_THRESHOLDS = [0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

# 静态障碍物参数
STATIC_OBSTACLE_PENALTY_MULTIPLIER = 1.5
STATIC_SAFE_DISTANCE = 5.0
ROAD_BOUNDARY_PENALTY = 10.0

# 交叉路口参数
INTERSECTION_SAFE_SPEED = 25.0
INTERSECTION_STEER_REDUCTION = 0.6

# 反应时间参数
REACTION_TIME_PENALTY = 0.1
PROACTIVE_REWARD = 0.5