name: Run Mujoco on Windows 

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Unity build
        shell: cmd
        run: |
          cd Unity
          build.cmd
